version: '3.8'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8080:443"
    depends_on:
      - php-fpm
    container_name: "nginx"
    networks:
      laravel-api-block:
        aliases:
          - api.local
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    environment:
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
    container_name: "php-fpm"
    networks:
      - laravel-api-block
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    tty: true
    depends_on:
      - postgres
    environment:
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
    container_name: "php-cli"
    networks:
      - laravel-api-block
  postgres:
    image: postgres
    container_name: "postgres"
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_MULTIPLE_DATABASES: "${DB_DATABASE},app_test"
    volumes:
      - "./storage/docker/pg-init-scripts:/docker-entrypoint-initdb.d"
      - "./storage/docker/postgresql:/var/lib/postgresql/data"
    networks:
      - laravel-api-block
  node:
    build:
      context: ./
      dockerfile: docker/node.docker
    volumes:
      - ./:/var/www
    tty: true
    container_name: "node"
    networks:
      - laravel-api-block
networks:
  laravel-api-block:
    driver: bridge
